# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/msm8939-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    /proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw\
    /proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw\
    /proprietary/vendor/firmware/a420_pfp.fw:system/vendor/firmware/a420_pfp.fw\
    /proprietary/vendor/firmware/a420_pm4.fw:system/vendor/firmware/a420_pm4.fw\
    /proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so\
    /proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so\
    /proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so\
    /proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so\
    /proprietary/vendor/lib/hw/vulkan.msm8916.so:system/vendor/lib/hw/vulkan.msm8916.so\
    /proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so\
    /proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so\
    /proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so\
    /proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so\
    /proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so\
    /proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so\
    /proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so\
    /proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so\
    /proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so\
    /proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so\
    /proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so\
    /proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so\
    /proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so\
    /proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so\
    /proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so\
    /proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so\
    /proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so\
    /proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so\
    /proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so\
    /proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so\
    /proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so\
    /proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so\
    /proprietary/vendor/lib/libllvm-qgl.so:system/vendor/lib/libllvm-qgl.so\
    /proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libloc_ds_api
